### ISSUE TITLE
Bad Authentication

### ISSUE THREAD

**Issue by EricBoily** [chvancooten/homeassistant-googletokenretriever#3]
hello, 
I'm always getting a BadAuthentication error.. I tried my password, I tried to generate an apppassword, I tried another account.. no luck.
is it still working or google change something?

[*] Getting master token...
{'Error': 'BadAuthentication'}
[!] Could not get master token.
[*] Master token: None

thanks

**Comment by chvancooten** [comment]
Hi @EricBoily,

Do you get this error if you manually run `python3 get_tokens.py`? If so, I'm guessing you are running into this issue:

https://github.com/simon-weber/gpsoauth/issues/24

Though it's not clear what exactly, it seems to be an issue with your combination of versions between Python and the Requests library. Try playing with upgrading/downgrading a bit as described in that issue, and it _should_ start working! 

Good luck!

**Comment by EricBoily** [comment]
Thanks for the answer, @chvancooten 

yes I get the error when I run `python3 get_tokens.py` on macos catalina.
I tried some downgrade suggested in the tread you linked without luck.  I'll keep digging on a clean linux installation.

thanks again.

**Comment by chvancooten** [comment]
Hi @EricBoily,

It looks like they recently closed the issue, pinpointing it to `urllib3`. Apparently you should use a version *below* 1.25.11 for it to work! Hopefully that works if you haven't tried it yet.

See here: https://github.com/simon-weber/gpsoauth/issues/24#issuecomment-774151318

Closing this issue for now (since it's not an issue with the token retriever script)
